Added new FAQs and context in the docs based on feedback in matrix
ansible/ansible-lightspeed pull request #26
Opened 2023-07-12 13:21 UTC by scottharwell

* Updated FAQ Page
* Added footer references to related FAQ questions
* Added new sections to installing extension and logging in
* Added `pre-commit` with markdownlint

2023-07-12 15:17 UTC, robinbobbitt requested changes

2023-07-12 15:17 UTC, robinbobbitt commented on docs/introduction.md
> +The Ansible VS Code extension, with Ansible Lightspeed with Watson Code Assistant features enabled, automatically collects recommendations, usage telemetry, and playbook state through automated event
nit: "is an important data" needs to be fixed

2023-07-12 17:52 UTC, scottharwell commented on docs/vscode_guide/installing_vs.md
> +To logout of Ansible Lightspeed, click on the "person" icon in the bottom-left panel of the VS Code window.  This icon will have a list of accounts that VS Code is logged into.  Click "Ansible Lights
Good call out.  Added.

2023-07-13 04:03 UTC, robinbobbitt requested changes
Looks great but needs two more super small edits.

2023-07-13 04:03 UTC, robinbobbitt commented on docs/introduction.md
> +The Ansible VS Code extension, with Ansible Lightspeed with Watson Code Assistant features enabled, automatically collects recommendations, usage telemetry, and playbook state through automated event
One more small edit: is used allows

2023-07-13 04:03 UTC, robinbobbitt commented on docs/vscode_guide/installing_vs.md
> +5. Click "Logout".
The button is actually two words: "Log out".

2023-07-13 10:51 UTC, scottharwell commented on docs/vscode_guide/installing_vs.md
> +5. Click "Logout".
Corrected.  And, VS Code uses "Sign Out" while the web page uses "Log Out"

2023-07-13 17:14 UTC, robinbobbitt approved these changes

2023-07-13 17:14 UTC, merged